- _information/Examination Schedules/Semester 1 Weighted Assessments.md
- index.md
Get ready for the new schedules
> WA2 updates

- pages/Latest News.md
> WA2 Latest News Link

- _information/Direct School Admission.md
We better have a mini microsite
> I Know How Already

- _people/Departments/Humanities.md
- index.md
> To update pictures in Humanities Webpage

- _people/Form Teachers/Secondary 1 Form Teachers.md
- _people/Form Teachers/Secondary 3 Form Teachers.md
- _people/Form Teachers/Secondary 4&5 Form Teachers.md
> Lets Do It - FT

- _people/Form Teachers/Secondary 4&5 Form Teachers.md
- _student-development-team/Counselling Services.md
> FT Update Ms Dee

- _information/Examination Schedules/Semester 2 Weighted Assessments.md
> Hyperlinks

- pages/Announcements.md
> New Announcement 9/7 WA Dates Topics

- _information/Examination Schedules/Preliminary Examination.md
- pages/Announcements.md
> Success N Schedule

- _information/Examination Schedules/Preliminary Examination.md
> Updating GCE N Prelims Page

- pages/Announcements.md
> HBL Announcements

- _people/Departments/Humanities.md
> HumanitiesDeptUpdating.Image

- _people/Departments/English Language & Literature.md
> EL Dept Photo

- _people/Departments/Mother Tongue.md
> My Photo 23

- _people/Departments/Mother Tongue.md
> MT Photo Update

- pages/Announcements.md
> Date Repairs

- _people/Departments/Physical Education & CCA.md
> PE Appointments

- _information/Examination Schedules/End of Year Examination.md
> Exam Schedules

- _information/Examination Schedules/End of Year Examination.md
> EOY Updates Hui Yee

- _happenings/Events/2023.md
- _people/Departments/Science.md
- _programmes/CCE Prog & PASSION Modules/2020.md
- _programmes/CCE Prog & PASSION Modules/2021.md
- _programmes/CCE Prog & PASSION Modules/2022.md
- _programmes/CCE Prog & PASSION Modules/CCE Programmes & PASSION Modules.md
- _programmes/collection.yml
> Science Dept

- _information/Why Choose Juying Secondary?/Why Choose Juying Secondary?.md
> Juying Publicity Booklet

- pages/Announcements.md
> information

- index.md
Announcement - Main Telephone Line Technical Issue
> Announcement - Main Telephone Line Technical Issue

- index.md
To delete the school's main line technical issue announcement.
> To delete the school's main line technical issue announcement
